roachtest: add tpcc/mixed-headroom on five nodes
Add a mixed version cluster variant of the headroom test. This gives us
a better shot at catching problems that occur only in the mixed
configuration.

It already caught a DistSQL incompatibility (since fixed):

> Error: check failed: 3.3.2.2: pq: rpc error: code = Unimplemented desc
> = unknown service cockroach.sql.distsqlrun.DistSQL

Release note: None