colexecerror: improve the panic-catcher
This commit updates the vectorized panic-catcher to not catch panics if
they came from the catcher itself. Previously, this would occur when we
have several levels of catchers with the inner-most determining that the
panic is not from the vectorized engine. This would result in
`panic(panicObj)` call, however, the catcher one level up would see that
the panic came from `CatchVectorizedRuntimeError` which is "within" the
vectorized engine, thus, the higher level catcher could do something
with it while it shouldn't.

This commit also starts treating packages with `pkg/sql/row` in the path
prefix (e.g. `rowexec`, `row`, `rowenc`) as part of the vectorized
engine too (previously, only `rowexec` was treated as such).

Additionally, this commit adds a utility method `NonVectorizedTestPanic`
that can be used by the testing code to simulate panics that occur
outside of the vectorized engine.

Release note: None