sql: sensible error when column default dropped in transaction
The COMMIT statement used to return
error: got 0 values but expected 1

The column backfiller's updateExprs[] was not being
initialized properly. A NULL default value reflects now in
a proper initialization of the default value to tree.DNull.

related to #26422

Release note: None