sql: fix AvgSize table stats references for mixed version clusters
`AvgSize` is a new `system.table_statistics` stat that is not found in
earlier CRDB versions. This led to a bug in multi-version clusters where
the table stats could not be collected or shown because of a reference
to an unknown column, as in the following example:

```
> ANALYZE t;
ERROR: get-table-statistics: column "avgSize" does not exist
> SHOW STATISTICS FOR TABLE t;
ERROR: read-table-stats: column "avgSize" does not exist
```

This change adds version gatekeeping to functions that access or write
to the field `AvgSize` in `system.table_statistics`. If the cluster
settings version is not at cluster version
`AlterSystemTableStatisticsAddAvgSizeCol`, functions such as
`ShowTableStats` and `InsertNewStat`, as well as the
`TableStatisticsCache`, revert to their old behavior without the new
`AvgSize` stat.

Manual testing on a multi-version cluster with nodes at version 21.2.2
and this change result in expected output for `ANALYZE` and
`SHOW STATISTICS`.

Release note: None