sql: validate index columns prior to creating index
Prior to this change, index creation would not validate the state of the index
until after the table descriptor had been updated. This was somewhat unfortunate
because it lead to an error in sqlbase which did not have an error code and did
not match up with postgres. This was more unfortunate because it led to an
assertion failure in the hash sharded index creation code.

Fixes #47037.

Before:

```
root@127.0.0.1:45631/movr> CREATE TABLE t1();
CREATE TABLE

root@localhost:26257/defaultdb> CREATE INDEX ON t1(c0);
ERROR: index "t1_c0_idx" contains unknown column "c0"

root@localhost:26257/defaultdb> CREATE INDEX ON t1(c0) USING HASH WITH BUCKET_COUNT = 8;
ERROR: hash sharded indexes require the experimental_enable_hash_sharded_indexes cluster setting
SQLSTATE: 0A000

root@localhost:26257/defaultdb> SET experimental_enable_hash_sharded_indexes = true;
SET

Time: 329.185µs

root@localhost:26257/defaultdb> CREATE INDEX ON t1(c0) USING HASH WITH BUCKET_COUNT = 8;
ERROR: internal error: could not find column family for the first column in the index column set
SQLSTATE: XX000
DETAIL: stack trace:
/go/src/github.com/cockroachdb/cockroach/pkg/sql/create_index.go:66: setupFamilyAndConstraintForShard()
...
```

After:
```
root@127.0.0.1:45631/movr> CREATE TABLE t1();
CREATE TABLE

root@127.0.0.1:45631/movr> CREATE INDEX ON t1(c0);
ERROR: column "c0" does not exist
SQLSTATE: 42703

root@127.0.0.1:45631/movr> CREATE INDEX ON t1(c0) USING HASH WITH BUCKET_COUNT = 8;
ERROR: column "c0" does not exist
SQLSTATE: 42703
```

Postgres:
```
postgres=# CREATE INDEX ON t1(c0);
ERROR:  42703: column "c0" does not exist
LOCATION:  ComputeIndexAttrs, indexcmds.c:1086
```

Release note (bug fix): Return proper error for index creation statements
using a column which does not exist.