kv: give savepoints distinct start and end sequence numbers
This commit increments a transaction's write sequence number on
savepoint creation and rollback. This ensures that savepoints have
distinct start and end sequence numbers, which is necessary distinguish
between all operations (writes and locking reads) that happened before
the savepoint creation, those that happened within the savepoint, and
those that happened after the savepoint rollback.

This avoids the problem described in the removed TODO. That hypothesized
problem is real. Without this change, #121088 runs into trouble with the
following sequence of operations:
```sql
create table kv (k int primary key, v int);
insert into kv values (1, 2);

begin isolation level read committed;
insert into kv values (2, 2);
savepoint s1;
insert into kv values (3, 2);
rollback to s1;
select * from kv where k = 1 for update;
commit;

ERROR: internal error: QueryIntent request for lock at sequence number 2 but sequence number is ignored [{2 2}]
```

Epic: None
Release note: None