tree: improve type checking for mixed-type arrays
Previously, certain binary operators involving two arrays with different
element types would fail at runtime, not at type-check time. This led to
the following oddity:

```
root@127.0.0.1:61739/defaultdb> create table z (a int[]);
CREATE TABLE

root@127.0.0.1:61739/defaultdb> select * from z where a @> array['foo'];
  a
-----
(0 rows)

root@127.0.0.1:61739/defaultdb> insert into z values(array[1]);
INSERT 1

root@127.0.0.1:61739/defaultdb> select * from z where a @> array['foo'];
ERROR: cannot compare arrays with different element types
SQLSTATE: 42804
```

It also was a potential source of bugs, since letting operators type
check that will never be allowed later can cause issues in SQL operators
like zigzag join that expect values to be comparable when the type
checker claims that they are.

This commit adds a simple rule that bans any cross-element-type array
operators, identically to the way that collated strings are
incomparable if they're of different collations.

Release note (sql change): operators on two arrays with different
element types now fail at type-check time instead of evaluation time.