cli: Make cert flag omissions much more obvious
Fixes part of #5433.

This commit makes sure the ssl flags are correctly set on our end before
sending a partially populated PGURL to lib/pq, or we'll end up with a
much more esoteric error. I'm not in love with how this ties values back
to the flags names, but I'm not sure of a better way without some
rearchitecting.

Instead of the delayed and misleading error from the issue listed above,
we now get:

```
Nathans-MacBook-Pro:cockroach$ ./cockroach sql --ca-cert=certs/ca.cert --cert=certs/node.cert
Error: missing --key flag
Failed running "sql"
```