workload/tpcc: move tpcc error checks before length checks
Some of the TPCC consistency checks ensure that the number of rows returned
by two queries is the same. This is done by checking that if one of the
iterators returns false, they both do. However, if one of the iterators
encounters an error, it will return false even though there are still rows
left. This could cause the consistency check to seem as if it failed with
incorrect results:
```
Error: check failed: 3.3.2.4: at 1682088974198157583.0000000000: length of order.sum(o_ol_cnt) != order_line.count(*)
```
when really one of the iterators just encountered an error. This patch moves
the error-checking before the length checking, so that the correct error
message is returned.

Fixes #102004

Release note: None