cli: Improve help message for debug zip command
Previously if you didn't provide a file argument, it would just print
out:

Error: exactly one argument is required
Failed running "debug"

Which doesn't indicate what argument is required and also kind of makes
it look like you were just running `cockroach debug`, not
`cockroach debug zip`.