pgerror: add "initial connection heartbeat failed" to SQL retryable
This commit adds `initial connection heartbeat failed` error to the list
of SQL retryable errors. `IsSQLRetryableError` is used in three places:
- rerunning distributed query as local
- `IsPermanentSchemaChangeError`
- `validateUniqueConstraint`

and in all cases I think it makes sense to consider failing to establish
a connection as a retryable error.

This commit includes the test from Jeff that exposed the gap in the
retry-as-local mechanism.

Release note: None