ccl,sql,util: Fix jwt auth and add sensitive error logs
We are running into issues with jwt authentication and currently unable to
provide support as we are not logging the error from the http client used in the
authenticator. The PR looks to propagate this obtained error from
`ValidateJWTLogin` http client. We are also introducing `JWTClientTimeout` and
`JWTClientCustomCA` cluster settings such that these could be configured
directly for the http client used in authenticator. The http client now also
respects the system http proxy if set and has a cluster setting
`JWTClientSystemProxyEnabled` to enable it.

Validated the error details when presenting an expired token
```
ERROR: JWT authentication: invalid token
SQLSTATE: 28000
DETAIL: unable to parse token: exp not satisfied Failed running "sql"
```

Validated error on setting wrong proxy params
```
ERROR: JWT authentication: unable to validate token
SQLSTATE: 28000
DETAIL: unable to fetch jwks: Get
"https://accounts.google.com/.well-known/openid-configuration": proxyconnect
tcp: dial tcp [::1]:3129: connect: connection refused
Failed running "sql"
```

Verified access logs after setting up squid proxy and passing env HTTP_PROXY and
HTTPS_PROXY params
```
1715103871.761    144 ::1 TCP_TUNNEL/200 5708 CONNECT accounts.google.com:443 -
HIER_DIRECT/74.125.200.84 -
1715103871.836     73 ::1 TCP_TUNNEL/200 5964 CONNECT www.googleapis.com:443 -
HIER_DIRECT/142.250.182.10 -
```

fixes https://github.com/cockroachdb/cockroach/issues/123575,
Epic CRDB-38386,

Release note(security update): We are adding 3 cluster settings
`server.jwt_authentication.client.timeout`,
`server.jwt_authentication.client.custom_ca` and
`server.jwt_authentication.client.system_proxy.enabled` which can control the
jwt auth behaviour for http client calls.