sql: add link to deprecation docs for cross db references in the error
Closes #57782

Release note (sql change): error messages for cross-database links now
include a hint directing to the user to the deprecation docs. An
example message looks like:

```
ERROR: the view cannot refer to other databases; (see the 'sql.cross_db_views.enabled' cluster setting)
SQLSTATE: 0A000
HINT: Note that cross database references will be removed in future releases. See: https://www.cockroachlabs.com/docs/releases/v21.1.0.html#deprecations
```