roachtest: improve/fix Jepsen error whitelist
The `invoke.log` often contained a chain of error causes like:
```
ERROR [2019-09-20 18:52:50,463] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
java.util.concurrent.ExecutionException: clojure.lang.ExceptionInfo: clj-ssh open-channel failure: session is down {:type :clj-ssh/open-channel-failure, :reason :clj-ssh/session-down}
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_222]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_222]
...
        at clojure.main.main(main.java:37) [clojure-1.8.0.jar:na]
Caused by: clojure.lang.ExceptionInfo: clj-ssh open-channel failure: session is down
        at clojure.core$ex_info.invokeStatic(core.clj:4617) ~[clojure-1.8.0.jar:na]
        at clojure.core$ex_info.invoke(core.clj:4617) ~[clojure-1.8.0.jar:na]
...
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_222]
Caused by: com.jcraft.jsch.JSchException: session is down
        at com.jcraft.jsch.Session.openChannel(Session.java:853) ~[jsch-0.1.53.jar:na]
        at clj_ssh.ssh$open_channel.invokeStatic(ssh.clj:540) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
```

This commit updates the grep to match against both the primary cause and
these secondary causes, which we've seen in flakes like #40946 would have
matched against the whitelist.

Release justification: Testing only.

Release note: None