vecerror: remove NonVectorizedPanic
This commit removes `vecerror.NonVectorizedPanic` in favor of
`vecerror.ExpectedError`. The guidance on whether `InternalError` or
`ExpectedError` method should be used has been updated: the distinction
is whether the vectorized engine ends up in an unexpected - invalid
- state (for example, we expect that the vectorized engine might be
performing division by zero when evaluating a binary expression).

Release note: None