sql: better inform the end-user about cluster virtualization
Release note (cluster virtualization): Two guardrails are available to
system operators to help with users upgrading from single-tenant,
non-virtualized CockroachDB to a deployment using cluster
virtualization.

Specifically, this is intended to help in cases where the user is not
connected to the "right" SQL interface to perform certain
configuration operations.

There are two guardrails included here:

- new cluster setting `sql.restrict_system_interface.enabled` to push
  the user towards using a virtual cluster for their application
  workload. When set, certain common operations that end-users
  may execute to set up an application workload are disallowed:

  - running DDL.

    For example:
    ```
    demo@127.0.0.1:26257/system/defaultdb> create database foo;
    ERROR: blocked DDL from the system interface
    SQLSTATE: 42501
    HINT: Object creation blocked via sql.restrict_system_interface.enabled to prevent likely user errors.
    Try running the DDL from a virtual cluster instead.
    ```

  - modifying an ApplicationLevel cluster setting.

    For example:
    ```
    demo@127.0.0.1:26257/system/defaultdb> set cluster setting ui.display_timezone = 'America/New_York';
    ERROR: blocked update to application-level setting from the system interface
    SQLSTATE: 42501
    HINT: Access blocked via sql.restrict_system_interface.enabled to prevent likely user errors.
    Try changing the setting from a virtual cluster instead.
    ```

- new cluster setting `sql.error_tip_system_interface.enabled` to
  enhance errors reported when a user mistakenly uses a storage-level
  SQL feature from a virtual cluster, to inform a user who might blindly
  follow an old runbook that they should use the system interface
  instead.

  For example, for setting that were previously application-level:
  ```
  demo@127.0.0.1:26257/demoapp/defaultdb> set cluster setting kv.rangefeed.enabled = true;
  NOTICE: ignoring attempt to modify "kv.rangefeed.enabled"
  HINT: The setting is only modifiable by the operator.
  Normally, an error would be reported, but the operation is silently accepted here as configured by "sql.error_tip_system_interface.enabled".
  ```

  And for settings that were always system-level:
  ```
  demo@127.0.0.1:26257/demoapp/defaultdb> set cluster setting trace.redact_at_virtual_cluster_boundary.enabled = false;
  ERROR: cannot modify storage-level setting from virtual cluster
  SQLSTATE: 42501
  HINT: Connect to the system interface and modify the cluster setting from there.
  ```

Release note (cluster virtualization): The predefined config profiles
related to cluster virtualization now automatically set the new
cluster settings `sql.restrict_system_interface.enabled` and `sql.error_tip_system_interface.enabled`.