batcheval: reject addsstable if store capacity remaining too low
```
➜  ./cockroach sql --insecure -e "SET CLUSTER SETTING kv.bulk_io_write.min_capacity_remaining_fraction = 0.75"
SET CLUSTER SETTING

➜ ./cockroach workload fixtures import tpcc --warehouses=10 --checks=false
I220325 23:56:17.451734 1 ccl/workloadccl/fixture.go:318  [-] 1  starting import of 9 tables
Error: importing fixture: importing table warehouse: pq: addsstable [/Table/106/1/0/0,/Table/106/1/9/0/NULL):
  insufficient remaining store capacity 648 GiB, or 69.9% to add sstable (min: 75.0%)

```

Release note (ops change): The setting kv.bulk_io_write.min_capacity_remaining_fraction
can now be set to cause bulk ingest operations like IMPORT, RESTORE or CREATE INDEX
to fail rather write to a node that is running out of disk space.