colexecerror: delete BenchmarkCatchVectorizedRuntimeError
This benchmark is now way too fast (100ns per op) so that random changes
in the binary result in "regressions".

Release note: None