importccl: adopt protected timestamps for IMPORT
Perhaps this only needed to be applied to IMPORT INTO but it doesn't hurt
import. This change ensures that IMPORT statements protect the spans into
which they'll be writing from being GC'd.

The change adopts the StartableJob change from the previous commit,
protects a timestamp, and then makes sure to clean up that timestamp
on success or failure.

Before this change the test added here would fail with the following error:

```
require.go:1104:
                Error Trace:    import_into_test.go:152
                Error:          Expect "pq: job 526896149330362369: cannot be reverted, manual cleanup may be required: rolling back partially completed IMPORT: cannot revert before replica GC threshold 1580866345.938283735,0" to match "error response from server: 500 Internal Server Error"
                Test:           TestProtectedTimestampsDuringImportInto
```

Release note (bug fix): IMPORT INTO jobs which are canceled or fail
can no longer get stuck in an unrecoverable state if data from the
previous state of the table had expired relative to the GC TTL.