sql: add infrastructure for rewriting computed column expressions
This commit adds infrastructure that allows automatic replacement of
computed column expressions in CREATE TABLE and ALTER TABLE
statements. This provides a workaround for cases where a computed
column expression is no longer allowed (because of better detection of
context-dependent operators) but the DDL statements cannot be easily
changed.

This is configured via a new, non-public cluster setting
`sql.computed_column_rewrites`. The value is a string of the form:
```
(before expression) -> (after expression) [, (before expression) -> (after expression) ...]
```

In order for a computed column to be rewritten, the entire computed
column expression must parse into the same AST as a "before
expression".

Example:
```
CREATE TABLE t (ts TIMESTAMPTZ NOT NULL, shard INT NOT NULL AS (mod(fnv32(ts::STRING), 4)) STORED);
ERROR: mod(): fnv32(): timestamptz::string: context-dependent operators are not allowed in computed column
SQLSTATE: 0A000
HINT: TIMESTAMPTZ to STRING casts depend on the current timezone; consider using (t AT TIME ZONE 'UTC')::STRING instead.

SET CLUSTER SETTING sql.computed_column_rewrites = "(mod(fnv32(ts::STRING), 4)) -> (mod(fnv32((ts AT TIME ZONE 'utc')::STRING), 4))";

CREATE TABLE t (ts TIMESTAMPTZ NOT NULL, shard INT NOT NULL AS (mod(fnv32(ts::STRING), 4)) STORED);

SHOW CREATE TABLE t;
  table_name |                                        create_statement
-------------+--------------------------------------------------------------------------------------------------
  t          | CREATE TABLE public.t (
             |     ts TIMESTAMPTZ NOT NULL,
             |     shard INT8 NOT NULL AS (mod(fnv32(timezone('utc':::STRING, ts)::STRING), 4:::INT8)) STORED,
             |     rowid INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
             |     CONSTRAINT "primary" PRIMARY KEY (rowid ASC),
             |     FAMILY "primary" (ts, shard, rowid)
             | )
```

Release note: None