colexecerror: do not catch runtime panics in crdb_test builds
CatchVectorizedRuntimeError performs its unusual stack-walking in order
to catch *all* panics originating from within the vectorized execution
engine, including runtime panics. The purpose of this is to limit the
impact of a bug in vectorized execution to failure of a single execution
rather than crashing the node.

During tests, however, we'd like to make these runtime panics louder,
since we believe they represent bugs in vectorized execution. So let's
not catch panics under crdb_test builds unless they're wrapped.

Epic: None

Release note: None