sql: provide more helpful error message when creating the wrong type of index
Previously, when a user attempts to create a forward index on a datatype that
does not support forward indexes, the error message is not very clear:

```
defaultdb> CREATE TABLE t (j JSON, INDEX ((j->'some_key')));
ERROR: index element j->'some_key' of type jsonb is not indexable
SQLSTATE: 42P16
```

The error message now suggests creating an inverted index.

Fixes #69589

Release justification: Low risk fix.

Release note (sql change): The error message when creating the wrong type of
index was not clear and it now suggests creating an inverted index.