scripts: make the release note extraction script search for common parent
Prior to this patch:

```
% python3 scripts/release-notes.py --from v2.0-alpha.20180122 --until bae7465a3
error: origin commit v2.0-alpha.20180122 not in history of bae7465a3160d68594613cc709ba3f05c12ee40f
```

After this patch:

```
% python3 scripts/release-notes.py --from v2.0-alpha.20180122 --until bae7465a3
warning: v2.0-alpha.20180122 is not an ancestor of bae7465a3!

The first common ancestor is 9da836000c7cc1ca058a4082a80c741c942b58c3,
which is 1 commits older than v2.0-alpha.20180122 and 2 days older. Using that as origin.

Changes 9da836000c7cc1ca058a4082a80c741c942b58c3 ... bae7465a3160d68594613cc709ba3f05c12ee40f
...
```