sql: prevent declarative-rules test churn when new versions are added
Fixes #102126

Previously, adding new 23.2 version results in this test failure:
```
Failed
=== RUN   TestDeclarativeRules/declarative_corpus_validation_standalone_command
[debug declarative-print-rules 1.1 op]
[debug declarative-print-rules 1000023.1-4 op]
[debug declarative-print-rules 1000023.1-4 dep]
    declarative_print_rules_test.go:46:
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/6812/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/cli/cli_test_/cli_test.runfiles/com_github_cockroachdb_cockroach/pkg/cli/testdata/declarative-rules/invalid_version:1:
        invalid_version [0 args]
        -----
        ----
        debug declarative-print-rules 1.1 op
        unsupported version number, the supported versions are:
         latest
         1000022.2
    declarative_print_rules_test.go:55:
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/6812/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/cli/cli_test_/cli_test.runfiles/com_github_cockroachdb_cockroach/pkg/cli/testdata/declarative-rules/oprules:1:

        expected:
        debug declarative-print-rules 1000023.1-2 op
        rules
        ----
        []

        found:
        debug declarative-print-rules 1000023.1-4 op
        rules
        ----
        []
    --- FAIL: TestDeclarativeRules/declarative_corpus_validation_standalone_command (0.06s)
```

This change ignores the version string after the `-`.

Release note: None