builtins: fix ceil and floor builtins not working with integer input
Fixes a bug where the `ceil` and `floor` builtin functions were not
working as expected with integer input.

Previously, these functions were returning an error:

```
> SELECT floor(1);
ERROR: unknown signature: floor(int)
SQLSTATE: 42883
```

With this change we are now able to do:

```
> SELECT floor(1);
  floor
---------
      1
(1 row)
```

Also standardises description for the two related builtins.

Related #45999

Release justification: This commit is safe for this release because the
change is trivial.

Release note (sql change): fix ceil and floor builtins not working with
integer input