pgerror: replace pgError with a pgerror.Error protobuf
In the original SQL code when we hit upon a SQL error
on the gateway node we would create a pgError on the gateway
node. In distsql, an error can happen on a remote node
during SQL execution which can translate into creating
a pgError on a remote node. This change changes pgError
to a protobuf so that it can be sent along to the gateway
node.