scripts/gceworker.sh: always populate username
In the previous change to this file we were to allow injecting a username.
The code before this commit, the code would populate the username as "" leading
to a leading `@` in the address. The `ssh` family of commands are happy enough
with this but the unison command is not. Before this change, we'd see:

```
Fatal error: ill-formed root specification ssh://@gceworker-ajwerner.us-east1-b.cockroach-workers/go/src/github.com/cockroachdb/cockroach
```

I'm content doing something different here like detecting whether we have
a username injected instead. I don't have a strong reason to do that but
maybe by explicitly making the user the output of `whoami` I'm preventing
some other customization.

Release note: None