colexecerror: catch panics from util/encoding
We recently saw a couple of cases where data corruption led to panics
when decoding that data. It is safe to catch such panics from
`util/encoding` package and convert them into internal errors since that
package doesn't deal with any mutexes or whatnot, so this commit
includes it into the allowlist for the vectorized panic catcher.

Epic: None

Release note: None