cli: set a timeout delay for SQL connections
This patch leverages a feature in the underlying SQL driver `lib/pq`
to set a connection timeout for all CLI commands that use a SQL
connection. This includes `cockroach sql`/`demo`, `cockroach node ls`,
`cockroach zone set`, etc.

The timeout is set to 5 seconds. If the client cannot connect within 5
seconds it fails with the following error:

```
Error: cannot dial server.
Is the server running?
If the server is running, check --host client-side and --advertise server-side.

read tcp [::1]:60205->[::1]:26257: i/o timeout
```

Release note (cli change): the various client commands that use a SQL
connection (including e.g. `cockroach sql`, `cockroach node`,
`cockroach user`) now produce an error if a connection could not be
established within 5 seconds instead of waiting forever.