pgerror: change pgError to contain a protobuf message
In the original SQL code we would hit upon a SQL error
on the gateway node and publish pgError on the gateway
node. In distsql, an error can happen on a remote node
during SQL execution which can translate into creating
a pgError on a remote node. This change adds a protobuf
to pgError so that it can be sent along to the gateway
node.