cli: fix `debug statement-bundle recreate`
Prior to this patch, `debug statement-bundle recreate` was failing with
the following error:

```
ERROR: unimplemented: cannot use SHOW LAST QUERY STATISTICS as a statement source
SQLSTATE: 0A000
```

The error happened because  SHOW LAST QUERY STATEMENT was sent to
the server as a *prepared statement*. This, in turn, was because
at that point the result type inference was enabled on the connection.

This was a latent bug that would be encountered by *any* command
trying to use the connection created by `clisqlcfg.MakeConn` before
the SQL shell was running (via the `.Run` method). This is because
result type inference is initially enabled (in `MakeConn`) then
disabled by `Run`.

It so happens that `debug statement-bundle recreate` was the first
where we noticed.

The fix is to ensure that the initial metadata gathering on the
connection is run with result type inference always disabled.

Release justification: non-production code changes

Release note: None