storage: make TestRaftRemoveRace race harder
This produces instant failures under stress:
```
0 runs so far, 0 failures, over 5s

--- FAIL: TestRaftRemoveRace (4.94s)
	client_test.go:915: change replicas of range 1 failed: result is ambiguous (Raft re-proposal failed: write at timestamp 0.000000123,1228 too old; wrote at 0.000000123,1229)
FAIL
```
This one is not new, and is tracked in #10969.
```
0 runs so far, 0 failures, over 5s

--- FAIL: TestRaftRemoveRace (7.24s)
	client_raft_test.go:1863: [n1,s1,r1/1:/M{in-ax}]: change replicas aborted due to failed preemptive snapshot: range=1: remote couldn't accept snapshot with error: [n2,s2],r1: cannot apply snapshot: [n2,s2]: canApplySnapshotLocked: cannot add placeholder, have an existing placeholder range=1 [/Min-/Max) (placeholder)
FAIL
```
This one needs to be investigated.

When the above failures are ignored, the test sometimes times out, even
when the timeout is increased to 5 minutes (the test normally takes
less than 10 seconds).

```
$ make stress STRESSFLAGS='-p 100 -stderr -maxfails 1 -ignore "(have an existing placeholder|result is ambiguous)"' PKG=./pkg/storage TESTS=TestRaftRemoveRace

```