engine: fix add regression test for batch.ApplyRepr
Before the fix, fails with

```
--- FAIL: TestBatchApplyRepr (0.00s)
         batch_test.go:255: old batch represents to:
           "\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x01\x05lost\x00\x06update"
           restored batch to:
           "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
FAIL
```

The fix is avoiding `Repr()` to assume we never flushed to RocksDB (which is
not true after `ApplyRepr()` since that goes directly to RocksDB).