schemaexpr: Remove checks for dropped or inaccessible column when replaceColumnVars
Previously, if we have a table with a column `col` and a constraint
referencing `col` and during the schema change of dropping `col`, concurrent
DML (e.g. INSERT) will use the default value (or NULL if no default) for
`col` when it still needs to write to the old primary index. If the
default value failed the constraint (when it's still enforced during
the schema change), it gives out a somewhat confusing error message:

```
ERROR: failed to satisfy CHECK constraint (crdb_internal_column_2_name_placeholder < 0:::INT8): column "crdb_internal_column_2_name_placeholder" does not exist, referenced in "crdb_internal_column_2_name_placeholder < 0:::INT8"
```

where the outmost error message is right ("failed to satisfy CHECK constraint")
but the inner error message is somewhat confusing -- it complains the
dropping column cannot be found. The root cause of this is because we
have logic such that if a check constraint is violated, we are going to
format that check constraint expression via `FormatExprForDisplay` but
it throws an error if any column in the expression is non-public or
inaccessible. This commit argues that, for schema changes, it is possible
to encounter column-in-mutation (i.e. non-public column) whenever we
need to format an expression so this commit removes the requirement, so
that the error message for the same concurrent DML will only have the
outmost error message

```
ERROR: failed to satisfy CHECK constraint (crdb_internal_column_2_name_placeholder < 0:::INT8)
```

It also adds a test to ensure that whenever the default value satisfies
the check constraint, concurrent DML stmts completes successfully.

Release note: None