tree: fix missing IsDistinctFrom support for VOID compared with NULL
Fixes #83754

Previously, the IS [NOT] [DISTINCT FROM] operators did not support
comparison of a VOID datum with NULL, as postgres supports.

This was inadequate because it also had the side-effect of causing some
queries which work in row execution to fail in vectorized execution with
an internal error. This is due to the unique property of a VOID, that it
can't be compared with another VOID using any of the normal operators
such as `=`, `<`, `>`..., or even IS [NOT] [DISTINCT FROM], for example:
```
SELECT ''::VOID IS DISTINCT FROM ''::VOID;
ERROR: unsupported comparison operator: <void> IS DISTINCT FROM <void>
SQLSTATE: 22023
```
Processing of COALESCE in the columnar execution engine for an
expression like `COALESCE(void_col, NULL)` builds a comparison between
the VOID column and NULL here:
https://github.com/cockroachdb/cockroach/blob/ea559dfe0ba57259ca71d3c8ca1de6388954ea73/pkg/sql/colexec/colbuilder/execplan.go#L2122-L2129

This comparison is assumed to be OK, but fails with an internal error
because comparison with `UnknownType` is only implicitly supported if
the type can be compared with itself.

To address this, this patch adds explicit support for comparison of
a VOID with an unknown type (NULL) in an Is[NOT]DistinctFrom operator,
so that when it involves these types, no error is returned. This matches
the behavior of postgres.

Release note (bug fix): This patch adds support for comparison of VOID
data with NULL via the IS [NOT] [DISTINCT FROM] operators. This fixes
internal errors which may occur when a VOID typed expression occurs in a
COALESCE SQL expression.