kv: support Rollback in Txn closure
This commit adds support for the following pattern in a transaction closure:

```go
db.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
    return txn.Rollback(ctx)
})
```

Surprisingly, this would previously return an error:
```
TransactionStatusError: client already committed or rolled back the transaction. Trying to execute: 1 EndTxn (REASON_UNKNOWN)
```

This was because the txn retry loop in `txn.exec` would attempt to commit the
rolled back transaction and encounter the `TransactionStatusError`. The loop is
now made aware of the client finalization state, and uses this to decide whether
to auto-commit.

Epic: None
Release note: None