ccl: debug encryption-active-key command to show active store key ID.
Given a data directory, this displays the active store key ID and
encryption algorithm in use.

Unlike `debug encryption-status`, this command does not open the
rocksdb instance and therefore does not require knowing the encryption
key. This makes it useful to determine the encryption status with zero
knowledge.

Sample outputs:
```
$ cockroach debug encryption-active-key foobar
Error: data directory foobar does not exist: stat foobar: no such file or directory
Failed running "debug encryption-active-key"

$ cockroach debug encryption-active-key cockroach-noencryption/
Plaintext:

$ cockroach debug encryption-active-key cockroach-plain/
Plaintext:

$ cockroach debug encryption-active-key cockroach-data
AES128_CTR:be235c29239aa84a48e5e1874d76aebf7fb3c1bdc438cec2eb98de82f06a57a0
```

Release note (enterprise change): add debug encryption-active-key
command