backupccl: deflake TestMetadataSST
This is a temporary fix for failures in TestMetadataSST.

First,

    backup_metadata_test.go:49: error executing 'BACKUP TO $1': pq: a
    CCL binary is required to use this statement type: *tree.Backup

is solved by moving the test back into the backupccl package so that
the plan hook for BACKUP is definitely registered.

Second,

    backup_metadata_test.go:89: file /0/BACKUP_MANIFEST does not exist
    in the UserFileTableSystem: external_storage: file doesn't exist

is solved by disabling tenants by default in the setup functions in
backuputils. There is duplication between these functions and the
functions in backupccl, where we already disable tenants. The error
above is likely the result of us directly using the internal executor
of the server to query the userfile storage, which may be incorrect if
we were actually talking to a tenant.

Release note: None