cli: better errors
Removed `panicGuard` and `mustUsage` and introduced proper error handling,
cleaning up some cruft along the way. However, the primary goal was exposing
better errors to clients. To this end, GRPC errors are now special-cased
and print a legible error. For example,

```
$ ./cockroach node ls # node is not even running
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

(error code 14: grpc: the connection is unavailable)
Failed running "node"
```

In particular, I removed the `failfast=false` toggle in RPCSender, which (at
least for the cli debug commands, where it is used) would have calls hang
forever, even if the server wasn't even running or the certificates not
specified.

Updated `grpcutil.IsConnectionClosed()` to operate on the `errors.Cause` of
an error.

Reworked `runQuit`:

```
./cockroach quit --host gamma.gce.cockroachdb.com # host alive, but secure
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

(error code 13: transport is closing)
Failed running "quit"

$ ./cockroach quit # host not running
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

(error code 14: grpc: the connection is unavailable)
Failed running "quit"

$  $ ./cockroach quit # node running
ok
```

Fixes #9151.
Fixes #9153.