grpcutil: Catch "closed connection" error when using tls
Since for some reason it's worded slightly differently than the non-tls
error. After securing the acceptance tests,cockroach quit flaked with
Error: Error sending drain request: rpc error: code = Internal desc = transport: tls: use of closed connection

Fixes #15158