dev: print informative message in case no tests are found
In this case Bazel reports an exit status of 4 which is propagated up to
`dev` with a pretty unhelpful message:

```
$ ./dev test pkg/release
$ bazel test pkg/release:all --test_env=GOTRACEBACK=all --test_output errors
DEBUG: bazel test pkg/release:all --test_env=GOTRACEBACK=all --test_output errors
INFO: Invocation ID: 62ed2e81-dbc8-4cfa-a446-b4e87bff160e
INFO: Analyzed target //pkg/release:release (0 packages loaded, 0 targets configured).
INFO: Found 1 target and 0 test targets...
Target //pkg/release:release up-to-date:
  _bazel/bin/pkg/release/release.a
INFO: Elapsed time: 0.370s, Critical Path: 0.20s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
ERROR: exit status 4
```

In this case we check whether the exit status was 4 and print an
appropriate message.

Release note: None