workload: error instead of crash when initial data is not supported
TPCH requires a go port of the initial data generation logic for
fixtures make to work, so it has an incomplete workload implementation.
In the meantime, error instead of crash.

    $ ./bin/workload fixtures make tpch
    Error: make fixture is not supported for workload tpch
    $ curl "http://localhost:8081/csv/tpch/nation"
    csv-server is not supported for workload tpch

There was already an error message for `init tpch`.

For #30155

Release note: None