roachpb.Error: remove Index
This information is already duplicated in the Detail, if it's present.
There's no need to maintain both, except for transiting non-proto
IndexedErrors, which is not being done anywhere.