sql: validate index name prior to creating index
Prior to this change, index creation would not validate the name of the
index until after the table descriptor had been updated. This lead to an
error in sqlbase which did not have an error code and did not match up
with postgres.

Touches #47430.

Before:

```
root@:26257/defaultdb> CREATE TABLE t (col1 int, col2 int);
CREATE TABLE

Time: 41.895671ms

root@:26257/defaultdb> CREATE INDEX col1_ind ON t (col1);
CREATE INDEX

Time: 485.49071ms

root@:26257/defaultdb> CREATE INDEX col1_ind ON t (col2);
ERROR: duplicate index name: "col1_ind"
```

After:
```
root@:26257/defaultdb> CREATE TABLE t (col1 int, col2 int);
CREATE TABLE

Time: 41.895671ms

root@:26257/defaultdb> CREATE INDEX col1_ind ON t (col1);
CREATE INDEX

Time: 485.49071ms

root@:26257/defaultdb> CREATE INDEX col1_ind ON t (col2);
ERROR: relation "col1_ind" already exists
SQLSTATE: 42P07
```

Postgres:
```
=> CREATE TABLE t (col1 int, col2 int);
CREATE TABLE
=> CREATE INDEX col1_ind ON t (col1);
CREATE INDEX
=> CREATE INDEX col1_ind ON t (col2);
ERROR:  42P07: relation "col1_ind" already exists
LOCATION:  index_create, index.c:821
```

Release note (bug fix): Return proper error for index creation statements
using an existing index name.