sql: exclude anonymous database from pg_catalog and pg_extension schemas in TableName.FQString()
Fixes #105929

`"".pg_extension.spatial_ref_sys` is the output of `TableName.FQString()` for
`spatial_ref_sys` which results in an error when trying to use the value:

```
demo@127.0.0.1:26257/movr> SELECT count(*) FROM pg_extension.spatial_ref_sys;
  count
---------
   6139
(1 row)

Time: 17ms total (execution 17ms / network 0ms)

demo@127.0.0.1:26257/movr> SELECT count(*) FROM "".pg_extension.spatial_ref_sys;
ERROR: cannot access virtual schema in anonymous database
SQLSTATE: 42704
HINT: verify that the current database is set
```

This PR fixes this by removing the `"".` prefix.

Release note: None