sql: improve statement-bundle recreate
Statement bundle recreate throws this error when starting:

ERROR: unimplemented: cannot use SHOW LAST QUERY STATISTICS as a statement source
SQLSTATE: 0A000

Fix it by disabling infer of result types which forces use of prepare
path which doesn't support observer statements.

Also if env.sql won't run just issue a warning since it usually has
nothing and frequently has invalid line breaks.

Release justification: non-production code
Release note: None