workload/schemachange: correct err codes
See change in #127545.

Additionally, setting a column's default to an unknown
type is an undefined object error. This is demonstrated below.
We also ensure that setting a column's default with an unknown
type short-circuits and returns a syntax error.

```
demo@127.0.0.1:26257/demoapp/movr> create table t(i int);
CREATE TABLE

Time: 9ms total (execution 7ms / network 1ms)

-- unknown type
demo@127.0.0.1:26257/demoapp/movr> alter table t alter
                                -> column i set default
                                -> 'irr':::enum;
ERROR: type "enum" does not exist
SQLSTATE: 42704
```

Informs: #122249

Release note: None