tree: fix type checking of IN subquery expressions
A query of the form `SELECT * FROM ab WHERE (a, b) IN (SELECT x+1, y+1 FROM xy)`
may error out:
```
ERROR: unsupported binary operator: <int> + <int> (desired <tuple{int, int}>)
SQLSTATE: 22023
```
But similar query `SELECT * FROM ab WHERE (a, b) IN (SELECT x, y FROM xy)`
does not error out.

In the former case, extra type checking is done, and we use the type of
the left expression as the desired type of the right expression.
However, there is a line of code to wrap the desired type in a tuple
since when type checking the right side subquery, we expect there to be
a tuple to peek into to get the desired type:
https://github.com/cockroachdb/cockroach/blob/b3d966c2e4f38d1da8536b0285a3d5d0d287016c/pkg/sql/opt/optbuilder/subquery.go#L94-L95

However, when the left is already a tuple, adding the extra tuple
layer may make it look like the desired type is tuple{tuple{int, int}},
for example, when it really should be tuple{int, int}.

The fix is to avoid wrapping the desired type in a tuple if it's already
a tuple.

Also, subquery building is updated to return error message
`(42601): subquery has too many columns`
or
`(42601): subquery has too few columns`
similar to Postgres, when appropriate.

Fixes: #63777

Release note (bug fix): This patch fixes handling of expressions in IN
clauses such as `(c1, c2) IN (SELECT c3+1, c4+1 FROM ...)`.
Previously such query expressions would error out during type checking.