sql: add a new cockroach specific pgcode
All cockroach tables need to have a primary key however
inside a txn a user can drop the primary key and then
attempt another operation on the table. This should return
a no primary key error.

Here is an example:

```
statement ok
BEGIN;
  ALTER TABLE t DROP CONSTRAINT primary;
  INSERT INTO t VALUES (1, 1)
COMMIT;
ERROR: requested table does not have a primary key
SQLSTATE: 55C02
```

Touches #47430.

Release note (bug fix): return a proper error cockroach specific error code
for trying to modify a table without a primary key instead of the
generic `XXUUU` error code.