sql/sem/builtins: improve an error
We were producing a very ugly error by wrapping a cause with a trace.
The trace, used as a message, completely obscured the error. This patch
makes the trace a "detail", which shows up nicely to SQL clients:

root@localhost:26257/defaultdb> select * from crdb_internal.probe_ranges(INTERVAL '1000ms', 'read') limit 1;
ERROR: error scanning meta ranges: !!! xxx
DETAIL: trace:
     0.000ms      0.000ms    === operation:meta2scan _verbose:1 client:127.0.0.1:40314 node:1 user:root
     0.009ms      0.009ms        === operation:txn coordinator send _verbose:1 client:127.0.0.1:40314 node:1 txnID:fa023bd2-91e3-4a75-94af-a07e537724ef user:root
     0.018ms      0.008ms            === operation:dist sender send _verbose:1 client:127.0.0.1:40314 node:1 txn:fa023bd2 user:root
     0.072ms      0.054ms            event:kv/kvclient/kvcoord/range_iter.go:175 [n1,client=127.0.0.1:40314,user=root,txn=fa023bd2] querying next range at /Meta2/"\x00"
     0.124ms      0.053ms            event:kv/kvclient/kvcoord/dist_sender.go:2032 [n1,client=127.0.0.1:40314,user=root,txn=fa023bd2] r1: sending batch 1 Scan to (n1,s1):1
     0.141ms      0.017ms            event:rpc/nodedialer/nodedialer.go:161 [n1,client=127.0.0.1:40314,user=root,txn=fa023bd2] sending request to local client
     0.147ms      0.005ms                === operation:/cockroach.roachpb.Internal/Batch _verbose:1 node:1 span.kind:server

Release note: None