sql: better error for exprs in ALTER PRIMARY KEY
Previously, a statement such as

  ALTER TABLE t ALTER PRIMARY KEY USING COLUMNS (gen_random_uuid())

would correctly fail because we don't allow expression-based primary
indexes, but the error message was rather obscure:

  ERROR: column "" does not exist

This patch provides a more useful error message.

Fixes #81522.

Release note: None