server: fix misleading TestJemalloc result for ppc64le
The test failed on ppc64le since the 16KiB constant in allocateMemory
didn't exceed the thread cache on ppc64le. Brief failure log shown below:
```
=== RUN   TestJemalloc
--- FAIL: TestJemalloc (0.00s)
    jemalloc_test.go:37: allocated stat not incremented on allocation: 2322976
```
Configuring jemalloc with `--disable-tcache to disable the thread cache` or
flushing thread cache as `mallctl("thread.tcache.flush", NULL, NULL, NULL, 0);`
showed expected behavior. But had performance and code clutter trade-offs resp.
So, updated the constant to suit ppc64le which also works for x86 and others.

Release justification: Fixes misleading test result for jemalloc stat on PPC
Release note: None