cli: Increase `debug doctor` scanner limit from 50MiB to 200MiB
We encountered a debug zip where its `system.jobs.txt` file contain
extrememly long line (>50MiB for that line), and cause commands within
`debug doctor` (e.g. `examine zipdir`) to fail with
```
ERROR: bufio.Scanner: token too long
Failed running "debug doctor examine zipdir"
```
This commit increases the scanner buffer limit from 50MiB to 200MiB
to handle those cases.

Release note: None