backupccl: support locality-aware incremental backups in SHOW BACKUP
Previously, SHOW BACKUP would only resolve incremental locations for
the first collection URI passed to SHOW BACKUP. As a result, SHOW
BACKUP on a backup that contained incrementals would result in an
error such as

    ERROR: expected manifest
    /20230510/160359.17/BACKUP_PART_1_zone=us-east not found in backup
    locations

This only affected `SHOW` because of code in `SHOW` designed to
support the user passing the URI to a specific full backup rather than
a collection and a subdirectory.

This commit changes the CollectionAndSubdir function to support an
array of backup locations.

Epic: none

Release note: Fixes a bug in which SHOW BACKUP would fail to show a
locality-aware backup that contained incremental backups.