roachtest: deflake disk-stalled roachtests
Fixes #51724, which failed with the salient error:

  ERROR: no --join flags provided to 'cockroach start'

Since this test is spinning up a single node cluster to test disk
stalls, it suffices to use start-single-node instead.

Release note: None