sql: fix statement generation when ensuring roles
Since we started skipping over non-existent roles in
35f723e3812a29f4b295c26885be706cc49ddd67, we need to make sure we only
add commas at the appropriate point.

The test update demonstrates that there was a bug before this patch, as
it would fail with:
```
expected:
ok defaultdb

found:
ERROR: LDAP authorization: error assigning roles to user ldap_user: EnsureUserOnlyBelongsToRoles-grant: at or near ",": syntax error (SQLSTATE 42601)
HINT: try \h GRANT
DETAIL: source SQL:
GRANT , "ldap-parent-synced" TO ldap_user
```

Release note: None