sql: fix check external connection evaluation
Previously, `CHECK EXTERNAL CONNECTION '' WITH CONCURRENCY = (SELECT 1)`
would panic because its not able to evaluate an expression containing a
sub query.

Now, passing a sub query will fail with a user error.

```
CHECK EXTERNAL CONNECTION NULLIF WITH CONCURRENTLY = EXISTS ( ( TABLE error ) );
ERROR: subqueries are not allowed in check_external_connection
SQLSTATE: 0A000
```

Release note: none
Informs: #147876
Informs: #147877