kvserver: deflake TestMaybeMarkReplicaUnavailableInLeaderlessWatcher
In #160692, this test failed with:

```
Error Trace:	pkg/kv/kvserver/replica_raft_test.go:495
Error:      	Expect "<nil>" to match "replica has been leaderless for 1m0s"
```

My suspicion is that under race, we are sometimes slow enough for the actual
raft tick to come around and mark us as having a leader.

Here, I set the RaftTickInterval to MaxInt32 and also add subtests so that it is
easier to know which subcase is failing if it fails again.

Fixes #160692
Release note: none