sql: implement an interlock to modify unsafe settings
Prior to this patch, it was possible to easily automate `SET CLUSTER
SETTING` for unsafe cluster settings. This is undesirable; we want to
strongly incentivize a human operator paying attention to changes to
these settings.

This patch implements an *interlock*: a mechanism through which the
operator needs to perform two concurrent, related actions for the
change to take effect.

This works as follows:

1. the operator attempts to change a cluster setting from a SQL shell,
   for example:

   ```sql
   SET CLUSTER SETTING kv.raft_log.synchronization.unsafe.disabled = true;
   ```

2. the server fails the execution, with an error:

   ```
   ERROR: changing cluster setting
   "kv.raft_log.synchronization.unsafe.disabled" may cause cluster
   instability or data corruption. To confirm the change, run the
   following command before trying again:

   SET unsafe_setting_interlock_key = 'B7TxIA==';

   ```

3. the operator can then perform the recommended action, then
   try SET CLUSTER SETTING again. Because the key is properly
   set, the SET CLUSTER SETTING statement succeeds.

Also, `RESET` statements (or `SET CLUSTER SETTING ... = DEFAULT`) are
not subject to the interlock, as we assume that the default value is
safe for use.

Release note: None