storage/engine: fix unnecessary C.ulonglong conversion
Something recently shook up the build, causing the following lint warnings
to start firing:

```
--- FAIL: TestLint/TestRoachLint (56.77s)
    lint_test.go:77:
        /Users/nathan/Go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:2216:35: unnecessary conversion
    lint_test.go:77:
        /Users/nathan/Go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:2217:35: unnecessary conversion
```

Release note: None