joberror: mark tenant shutdown error as non-permanent bulk job error
This commit marks errors that can occur due to tenant shutting down as
"non permanent bulk job" errors which will make it so that the bulk job
is retried automatically. In particular, we've observed in an import
test - when ran against the test tenant - that has a node failure
(simulated by stopping the server) that `addstable` request can fail due
to tenant shutdown, and this commit makes it so that we retry in
situations like this.

Release note: None