ldapccl: add detailed errors for incorrectly configured HBA service user
fixes #133231
Epic CRDB-33829

Currently, for any of the operations performed on AD server like user DN lookup
or group listings for a user, we just provide a generic failure message:
```
LDAP authentication: unable to find LDAP user distinguished name
```
In the case where service user credentials are invalid(provided via ldapbinddn
and ldapbindpasswd in HBA conf, we would like to show that failure was because
of incorrectly configured credentials.

This changes addresses the issue by adding appropriate client error messages and
additional detailed error logging.

Release note(security): We add detailed client error messages in case of
incorrect service account credentials for ldap authentication and authorization.
The error message will be as follows:
```
ERROR: LDAP authentication: error binding as LDAP service user with configured credentials (SQLSTATE 28000)
```