pgerror: clean up API
The various public-facing functions in pgerror have a number of
inconsistencies:
 - some functions start with `New`, others don't
 - the `f` suffix isn't used consistently (like `Unimplemented`, which
   caused unnecessary `Sprintf`s in some callers)
 - some functions contain `Error`, others don't.

This commit cleans this up:
 - we remove `Error` because it is redundant with the package name
 - we remove `New` for all wrappers
 - we make all wrappers have `f` and non-`f` versions.

Release note: None