changefeedccl: remove flaky assertion
This was failing on unrelated PRs:

    Failed
    === RUN   TestChangefeedMonitoring/sinkless
    changefeed_test.go:1697: expected > 0 got 0
    --- FAIL: TestChangefeedMonitoring/sinkless (12.04s)

I believe this is because the test setup for the metrics isn't
guaranteed to produce any wait time in the schema feed. We could hit
the fast path or our waiter could complete before we even start the
timer.

Release note: None