pgerror: add severity concept to pgerror package
`pgwire` will need to send down severities which  can be customised by
the developer.

To accomplish this, we introduce severity to the pgerror package, which
includes the helper functions `WithSeverity` and `GetSeverity`.
Developers who specify a severity using WithSeverity will now see that
severity pop up over the wire. The default severity if none is specified
is ERROR.

This has been plugged in for NOTICE using `Noticef`.

Release note: None