sqlccl: retry failed splits on AmbiguousResultErrors
RESTORE presplits sometimes fail due to ambiguous result errors, which
then fails the entire restore. Here's an example of such an error that
reproduced readily on a 2TB RESTORE into a cluster with existing data:

    Error: pq: presplitting 16384 ranges: storage/replica_command.go:2712: split at key /Table/53/1/6893975069665253839/"59ebe116-939c-4a40-83ae-b53652393a8b"/9561153 failed: result is ambiguous (error=TransactionRetryError: retry txn "split" id=0355ab32 key=/Local/Range/"\xbd\x89\xfd_\xa8H\x99]\xcb\u07b7\x12bc82cd3b-3091-4ced-a307-fa2f939e3da3\x00\x01\xf8\x04\xc0E"/RangeDescriptor rw=true pri=0.01067854 iso=SERIALIZABLE stat=PENDING epo=0 ts=1495044332.741237574,2 orig=1495044249.173005863,0 max=1495044249.173005863,0 wto=false rop=false seq=2, pending RPCs=1)

This patch, which extends AdminSplit's internal retry loop to retry
AmbiguousResult errors, made the problem completely vanish for me.