cli: Make cert flag omissions much more obvious
Fixes part of #5433.

This commit makes sure the ssl flags are correctly set on our end before
sending a partially populated PGURL to lib/pq, or we'll end up with a
much more esoteric error.

Instead of the delayed and misleading error from the issue listed above,
we now get:

```
Nathans-MacBook-Pro:cockroach$ ./cockroach sql --ca-cert=certs/ca.cert --cert=certs/node.cert
Error: missing --key flag
Failed running "sql"
```

This was accomplished by creating a FlagMap to `base.Context`. The map
relates values back to the flags which set them, and is general enough
to be used for other situations like this in the future.