opt: prevent stack overflows when there is a memo cycle
Misbehaving exploration rules can cause cycles in a memo, where a path
exists from a group member's children back to the group member's group.
In the example below, notice the cycle `G1 -> G6 -> G1`.

These cycles cause stack overflow errors and crash nodes. In addition,
they can be very difficult to debug because the cycle is not easily
observable.

This commit adds a mechanism to detect memo cycles. Once detected, the
optimizer throws an internal error, preventing a stack overflow. The
error detail includes the formatted output of the memo to aid in
debugging the cycle.

Below is an example of the error message displayed in the SQL shell when
a memo cycle is detected.

    ERROR: internal error: memo group optimization passes surpassed limit of 100000; there may be a cycle in the memo
    SQLSTATE: XX000
    DETAIL: memo (not optimized, ~17KB, required=[presentation: a:1,a:5,b:6,shard:7] [distribution: us-east1])
     ├── G1: (left-join G2 G3 G4) (right-join G3 G2 G4) (lookup-join G2 G5 t@t_shard_b_idx,outCols=(1,5-7)) (project G6 G7 a a b)
     ├── G2: (scan small,cols=(1))
     │    └── []
     │         ├── best: (scan small,cols=(1))
     │         └── cost: 1084.62
     ├── G3: (project G8 G9 a b)
     │    └── []
     │         ├── best: (project G8 G9 a b)
     │         └── cost: 1124.84
     ├── G4: (filters G10)
     ├── G5: (filters)
     ├── G6: (left-join G2 G8 G4) (right-join G8 G2 G4) (project G1 G11 a a b)
     ├── G7: (projections G12)
     ├── G8: (scan t,cols=(5,6)) (scan t@t_shard_b_idx,cols=(5,6))
     │    └── []
     │         ├── best: (scan t,cols=(5,6))
     │         └── cost: 1104.82
     ├── G9: (projections G13)
     ├── G10: (eq G14 G15)
     ├── G11: (projections)
     ├── G12: (case G16 G17 G13)
     ├── G13: (minus G15 G18)
     ├── G14: (variable small.a)
     ├── G15: (variable b)
     ├── G16: (is G19 G20)
     ├── G17: (scalar-list G21)
     ├── G18: (const 1)
     ├── G19: (variable t.a)
     ├── G20: (null)
     ├── G21: (when G22 G23)
     ├── G22: (true)
     └── G23: (null)
    stack trace:
    github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:454: optimizeGroup()
    github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:262: optimizeExpr()
    github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:534: optimizeGroupMe
    mber()
    ...

Also, a new optimizer test directive, `expropt`, has been added to
facilitate testing of this memo cycle detection.

Release note: None