sql: validate column name prior to adding or renaming a column
Prior to this change, add or renaming a column would not validate that
the column name does not exist until after the table descriptor had been
updated.  This lead to an error in sqlbase which did not have an error
code and did not match up with postgres. This PR categorizes such errors
as `pgcode.DuplicateColumn`. Also empty column name error is categorized
as `pgcode.Syntax` error.

Touches #47430.

Before:
```
root@:26257/defaultdb> CREATE TABLE t (col1 INT, col1 FLOAT);
ERROR: duplicate column name: "col1"
root@:26257/defaultdb> CREATE TABLE t (col1 INT, col2 FLOAT);
CREATE TABLE
root@:26257/defaultdb> ALTER TABLE t ADD COLUMN col2 INT;
ERROR: duplicate column name: "col2"
root@:26257/defaultdb> ALTER TABLE t RENAME COLUMN col2 TO col1;
ERROR: column name "col1" already exists
```

After:
```
root@:26257/defaultdb> CREATE TABLE t (col1 INT, col1 FLOAT);
ERROR: duplicate column name: "col1"
SQLSTATE: 42701
root@:26257/defaultdb> CREATE TABLE t (col1 INT, col2 FLOAT);
CREATE TABLE
root@:26257/defaultdb> ALTER TABLE t ADD COLUMN col2 INT;
ERROR: column "col2" of relation "t" already exists
SQLSTATE: 42701
root@:26257/defaultdb> ALTER TABLE t RENAME COLUMN col2 TO col1;
ERROR: column "col1" of relation "t" already exists
SQLSTATE: 42701
```

Postgres:
```
spas-> CREATE TABLE t (col1 INT, col2 FLOAT);
ERROR:  42601: syntax error at or near "ERROR"
LINE 1: ERROR: column "col1" of relation "t" already exists
        ^
LOCATION:  scanner_yyerror, scan.l:1127
spas=> CREATE TABLE t (col1 INT, col2 FLOAT);
CREATE TABLE
spas=> drop table t;
DROP TABLE
spas=> CREATE TABLE t (col1 INT, col1 FLOAT);
ERROR:  42701: column "col1" specified more than once
LOCATION:  MergeAttributes, tablecmds.c:1742
spas=> CREATE TABLE t (col1 INT, col2 FLOAT);
CREATE TABLE
spas=> ALTER TABLE t ADD COLUMN col2 INT;
ERROR:  42701: column "col2" of relation "t" already exists
LOCATION:  check_for_column_name_collision, tablecmds.c:5568
spas=> ALTER TABLE t RENAME COLUMN col2 to col1;
ERROR:  42701: column "col1" of relation "t" already exists
LOCATION:  check_for_column_name_collision, tablecmds.c:5568
```

Release note (bug fix): Return proper error for trying to ADD or RENAME
a column with an existing name.