deploy: update container build instructions
The documentation for building a container image of CockroachDB locally
was missing a step to copy the `licenses` directory into `build/deploy`,
leading to the following error when attempting a `docker build`:

```
STEP 7/13: COPY licenses/* /licenses/
Error: building at STEP "COPY licenses/* /licenses/": checking on sources under "/var/tmp/libpod_builder2005735694/build": Rel: can't make  relative to /var/tmp/libpod_builder2005735694/build; copier: stat: ["/licenses/*"]: no such file or directory
```

This patch updates the build instructions with the steps needed to build
a local container image of CockroachDB.

Epic: none

Release note: None