roachtest: add tpcc/mixed/nodes=3/headroom
Add a mixed version cluster variant of the headroom test. This gives us
a better shot at catching problems that occur only in the mixed
configuration.

It already seems to be catching something because the import checks
immediately fail with

> Error: check failed: 3.3.2.2: pq: rpc error: code = Unimplemented desc
> = unknown service cockroach.sql.distsqlrun.DistSQL

Release note: None