scripts: make the release note extraction script search for common parent
Prior to this patch:

```
% python3 scripts/release-notes.py --from v2.0-alpha.20180122 --until 20555d03b
error: origin commit v2.0-alpha.20180122 not in history of 20555d03b500515ae492e7d9a13988afa22ae5d4
```

After this patch:

```
% python3 scripts/release-notes.py --from v2.0-alpha.20180122 --until 20555d03b
warning: v2.0-alpha.20180122 is not an ancestor of 20555d03b!

The first common ancestor is 285270fcedd78cf1b6696f3044deea1f2092454c,
which is 1 commits older than v2.0-alpha.20180122 and 2 days older. Using that as origin.

Changes 285270fcedd78cf1b6696f3044deea1f2092454c ... 20555d03b500515ae492e7d9a13988afa22ae5d4
...
```