concurrency: update wait queues in AddDiscoveredLock
Concurrent readers in the face of a concurrent, retrying writer can
result in a situation where AddDiscoveredLock moves the timesamp of a
held intent past the read timestamp a waiting reader. The reader
should be unblocked in this case but previously wasn't, resuling in a
lock table verification assertion failure in the form of:

   error: non locking reader ... does not conflict with lock holder

This is my best theory for what is happening in #146749 based on
increased logging. It is difficult to be certain given the required
ordering of events is hard to observe with locking.

See the comment in the test for a more complete timeline that can lead
to the bug.

Fixes #146749

Release note: None