jobs: potentially fix flake in TestRetriesWithExponentialBackoff
This potentially fixes an error we've seen when attempting to stress
this test. Namely, we occasionally see:

```
=== RUN   TestRetriesWithExponentialBackoff/pause_running
    registry_test.go:796:
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/jobs/registry_test.go:796
        	                github.com/cockroachdb/cockroach/pkg/jobs/registry_test.go:873
        	Error:      	Not equal:
        	            	expected: 41
        	            	actual  : 40
        	Test:       	TestRetriesWithExponentialBackoff/pause_running
        	Messages:   	unexpected number of jobs resumed in
                retry 40
```

What I _think_ is happening here is that the adopt loop is able to
run twice before the paused job actually exits its Resumer. So,
waiting for the adopt loop to run twice isn't actually enough to
guarantee we've tried to resume the job already.

In this change, I wait on the resumed metric to advance which should
only advance once we've actually decided to call the resumer.

Locally, this failure mode is _very_ rare, so it is hard for me to say
whether this fixes the problem completely.

Informs #112763

Release note: None