cli: hint missing --join upon already-init errors
Before:

```
Error: rpc error: code = Unknown desc = cluster has already been initialized
Failed running "init"
```

After:

```
Error: rpc error: code = Unknown desc = cluster has already been initialized
HINT: Please ensure all your start commands are using --join.
Failed running "init"
```

Release note (cli change): The error message produced by `cockroach
init` when it encounters an already-initialized cluster has been
extended with a hint to recommend adding `--join` to the start
commands.