colexecerror: remove BenchmarkCatchVectorizedRuntimeError
Now that we've improved CatchVectorizedRuntimeError this benchmark isn't
measuring anything substantive, and is prone to strange regressions that
are false positives. Delete it.

Epic: None

Release note: None