sql: fix issue with database name when converting privilege to default privilege
Release note (sql change): Fix bug when granting incompatible database
privilege to default privilege with non-lowercase database names.

In a previous commit, SELECT, INSERT, UPDATE, DELETE were removed as
database privileges. They were instead automatically converted to
default privileges on the database. However the converted statement
had an issue with non-lowercase names.

Example: Grant SELECT on "AppDB" would fail because the converted
statement would look for "appdb" instead of "AppDB" because the casing
was not kept.

grant select on database "AppDB" to devuser;
ERROR: database "appdb" does not exist
SQLSTATE: 3D000