cli/sql: enhance the introductory comment
This patch enhances the message printed upon startup by `cockroach
sql` in interactive sessions.

Before this patch:

    $ ./cockroach sql
    # Welcome to the cockroach SQL interface.
    # All statements must be terminated by a semicolon.
    # To exit: CTRL + D.
    #
    root@localhost:26257/>

After this patch:

    $ ./cockroach sql
    # Welcome to the cockroach SQL interface.
    # All statements must be terminated by a semicolon.
    # To exit: CTRL + D.
    #
    # Enter \? for a brief introduction.
    #
    root@localhost:26257/>

Or in case of connection errors:

Before this patch:

    $ ./cockroach sql --host=nonexistent
    Error: unable to connect or connection lost.
    [...]
    Failed running "sql"

After this patch:

    # Welcome to the cockroach SQL interface.
    # All statements must be terminated by a semicolon.
    # To exit: CTRL + D.
    #
    Error: unable to connect or connection lost.
    [...]
    Failed running "sql"

(Why: this way, any reporting done about the SQL session while the
connection is being set up will appear after the welcome message.)