sql: introduce SHOW TENANT <name>
This change adds:

`SHOW TENANT <name>`

To show the id, name and status of the tenant. The status can be
ACTIVE/ADD/DROP.

The next step is to extend this to show replication status (more details
in #91261).

For example:
```
root@localhost:26257/defaultdb> show tenant my_tenant;
  id |   name    | status
-----+-----------+---------
   6 | my_tenant | ACTIVE
(1 row)

Time: 2ms total (execution 2ms / network 0ms)

root@localhost:26257/defaultdb> show tenant not_my_tenant;
ERROR: tenant "not_my_tenant" does not exist
SQLSTATE: 42704
```

Informs: #91261

Release note: None

Epic CRDB-18749