roach{prod,test}: harden grafana installation
Installing grafana through the APT repository upstream got busted
(didn't look into why/how/when). But installing the .deb package by
wget-ting it works so just do that instead:

  $ roachprod grafana-start irfansharif-1667423209-01-n4cpu8
  [...]
  deb https://packages.grafana.com/enterprise/deb stable main
  E: The repository 'https://packages.grafana.com/enterprise/deb stable Release' does not have a Release file.
  [...]
  21:21:18 cluster_synced.go:799: error - retrying: COMMAND_PROBLEM: exit status 100

Also fix prometheus scraping of the TPC-C workload generator in TPC-C
harness.

Release note: None