colexecerror: move out of colexecbase directory
`colexecerror` is used by many packages and deserves to be top-level
folder in `sql` directory.

Release note: None