bazel: add cross-toolchain targeting macOS
We follow up on previous commits that introduce cross-compilers for
Linux and Windows with a final one that builds for macOS.

The new toolchain files are in `build/toolchains/darwin-x86_64` -- we
don't reuse `build/toolchains/crosstool-ng` because we don't actually
use `crosstool-ng` for the Darwin toolchain, so things are actually
quite different under the hood.

We also pull in a new `rules_go` commit to handle an obscure bug.
Without it, builds using the cross toolchain end with an error like
this:

    ERROR: /cockroach/pkg/cmd/cockroach-short/BUILD.bazel:14:10: GoLink pkg/cmd/cockroach-short/cockroach-short_/cockroach-short failed: (Exit 1): process-wrapper failed: error executing command
      (cd /root/.cache/bazel/_bazel_root/cc377fc379544923cc7508dd261e4a48/sandbox/processwrapper-sandbox/961/execroot/cockroach && \
      exec env - \
      ...
        PATH=external/toolchain_cross_x86_64-apple-darwin19/bin:/bin:/usr/bin \
      ...
      /root/.cache/bazel/_bazel_root/install/1a4a2fac02d50c77031d44c0d91b8920/process-wrapper '--timeout=0' '--kill_delay=15' bazel-out/host/bin/external/go_sdk/builder '-param=bazel-out/k8-fastbuild/bin/pkg/cmd/cockroach-short/cockroach-short_/cockroach-short-0.params' -- -extld external/toolchain_cross_x86_64-apple-darwin19/bin/x86_64-apple-darwin19-cc '-buildid=redacted' -extldflags '-L/root/.cache/bazel/_bazel_root/cc377fc379544923cc7508dd261e4a48/external/toolchain_cross_x86_64-apple-darwin19/lib --sysroot=/root/.cache/bazel/_bazel_root/cc377fc379544923cc7508dd261e4a48/external/toolchain_cross_x86_64-apple-darwin19/SDK/MacOSX10.15.sdk') process-wrapper failed: error executing command
    external/go_sdk/pkg/tool/linux_amd64/link: external/go_sdk/pkg/tool/linux_amd64/link: running dsymutil failed: xcrun resolves to executable relative to current directory (./external/toolchain_cross_x86_64-apple-darwin19/bin/xcrun)

This error comes from the golang toolchain, specifically
[this commit](https://github.com/golang/go/commit/953d1feca9b21af075ad5fc8a3dad096d3ccc3a0)
which landed in Go 1.16. Go courageously refuses to run executables that
are relative to the current path, since (particularly on Windows) this
is very liable to introduce remote code execution bugs. Bazel routinely
uses relative paths in the `PATH` environment variable, however. To
address this we just add a small function to munge the `PATH` to contain
absolute paths whenever we're linking.

Release note: None