c-deps: bump RocksDB from 5.13 to 5.17.2
Pass `USE_RTTI=1` to the RocksDB build. 5.13 was built with rtti
enabled (there was no way to disable it), but 5.17.2 defaults to
disabling rtti. Unfortunately, the rest of our C++ dependencies build
with rtti enabled and C++ requires consistently specifying `-fno-rtti`
for all compilation, otherwise you get strange `undefined reference to
typeinfo` errors at link time. At least one of our C++
dependencies (cryptopp) does not allow easily disabling usage of rtti.

Verified that the `RocksDBDeleteRangeIterate` benchmark was unchanged
which indicates the RocksDB delete range patches are in effect.

Release note: None