sql: fix statement-bundle recreate
Statement bundle recreate throws this error when starting:

```
ERROR: unimplemented: cannot use SHOW LAST QUERY STATISTICS as a statement source
SQLSTATE: 0A000
```

Fix it by disabling infer of result types which forces use of prepare
path which doesn't support observer statements.

Release justification: non-production code
Release note: None