cli: inject some last-minute version checks
2.0 CLI commands are variously incompatible with 1.0 and 1.1 CockroachDB
clusters. Apply some emergency stopgaps to print out nice error
messages. For example, running `cockroach init` against a 1.0 cluster
now prints out

    incompatible client and server versions (likely server version: v1.0, required: >=v1.1)

instead of:

    Error: rpc error: code = Unimplemented desc = unknown service cockroach.server.serverpb.Init

The `cockroach node` commands, which are also incompatible with 1.0
clusters, get a similar treatment.

The `cockroach dump`, `cockroach user`, and `cockroach zone` print out
similar version errors based on their particular required version:

    Error: incompatible client and server versions (detected server version: 1.1.5, required: >=v1.2-alpha.20171026)

The `dump`, `user`, and `zone` command use the SQL interface where
precise version information is available; `init`, `node`, and `quit` use
the GRPC interface where the server version must be inferred from the
error messages returned.

Future CLI work should try harder to maintain compatibility with old
Cockroach servers; for 2.0, though, we're both out of time and don't
have the infrastructure in place to test the CLI against old servers.

Release note (cli change): The CLI produces better error messages when
connecting to a server with an incompatible version.