kv/concurrency: deflake TestContentionEventTracer
I was occasionally seeing this flake with errors like:
```
--- FAIL: TestContentionEventTracer (0.00s)
    assertion_compare.go:332:
        	Error Trace:	lock_table_waiter_test.go:1000
        	Error:      	"178µs" is not less than "178µs"
        	Test:       	TestContentionEventTracer
        	Messages:   	[]
```

This was because the test was expecting passage of time in the system
clock between two events. This commit resolves the issue by eliminating
the dependency on the system clock.