workload: synchronise concurrent access to preparedStatements map
After 60dd572e, the TPCC workload started to fail with

```
fatal error: concurrent map writes
```

because it attempts to start multiple sq runners using the same
MultiConnPool. This fix allows for that by putting a mutex around the
map accesses.

Fixes #69745
Fixes #69744
Fixes #69743
Fixes #69742
Fixes #69741
Fixes #69739
Fixes #69738
Fixes #69735
Fixes #69734

Release justification: Fixes critical bug in TPCC workload.

Release note: None