colexecerror: improve BenchmarkSQLCatchVectorizedRuntimeError
Previously, this benchmark when run with `conns=50` parameter would
often hit errors seemingly due to port exhaustion. This was the case
since the benchmark opens a ton of connections, but they would only be
closed on the server shutdown. This commit fixes that issue by
explicitly closing the connection from each worker goroutine once the
worker is done with it.

Additionally, it reduces the conns parameters from 20 and 50 to 8 and 32
in order to speed up the benchmark overall.

Release note: None