upgrades: fix TestKeyVisualizerTablesMigration
This test started failing for commits that introduced additional version
gates, like in #95748. It's because we were not overriding the binary
version the server started off with (it defaults to the last added
version). It failed with:

  Error Trace:	pkg/upgrade/upgrades/helpers_test.go:67
                pkg/upgrade/upgrades/helpers_test.go:50
                pkg/upgrade/upgrades/key_visualizer_migration_test.go:48
  Error:      	pq: versions cannot be downgraded (attempting to downgrade from 1000022.2-34 to 1000022.2-32)

Release note: None