pgerror: avoid wrapping special roachpb errors
Prior to this patch, the following scenario was possible:

1. some SQL function A() calls client.Txn() to call B() on its behalf
   with a retry loop.
2. client.Txn() calls B()
3. B() runs KV operation, encounters some *roachpb.RetryError
4. B() calls `pgerror.Wrap()` on that retry error, turns it into pg
   error with code 40001
5. B() returns into client.Txn()
6. client.Txn() tests the type of the error expecting to find a
   roachpb error for retries. Because it's a pgerror now, the test
   fails and the retry error is not handled automatically. It flows
   out.
7. A() receives a retry error when it was not expecting any.

The error would incur spurious DDL failures, with the following
example:

```
--- FAIL: TestLogic/fakedist-opt/computed (2.66s)
    logic.go:2346:

        testdata/logic_test/computed:687:
        expected:
        division by zero

        got:
        pq: column "d" being dropped, try again later
```

(This particular test would fail after just a few attempts during a
stress run.)

This patch fixes this scenario by ensuring that retry and ambiguous
result errors flow through `pgerror.Wrapf` without being flattened
into a `pgerror.Error`, and instead remain wrapped as the original
cause via `errors.Wrapf`.

The patch is verified to work by stress testing the logic tests and
verifying that the various error symptoms do not occur any more.

Additionally, two missing calls to `errors.Cause()` were added to
ensure any enclosed roachpb error is visible to a type check.

Release note: None