execerror: catch panics from sql/colcontainer package
We added a new package `sql/colcontainer` that uses panic-catch
mechanism of error propagation, but we forgot to "register" it with the
catcher, and now this is fixed.

Release note: None