sql: implement FILTER clauses for aggregate expressions
This is a nifty feature introduced in SQL:2003 and supported by Postgres
since 9.4.
If FILTER is specified in an aggregation expression, then only the
input rows for which the filter clause evaluates to true are fed to the
aggregate function; other rows are discarded. For example:

SELECT
    count(*) AS unfiltered,
    count(*) FILTER (WHERE i < 5) AS filtered
    FROM generate_series(1,10) AS s(i);
unfiltered | filtered
-----------+----------
10         | 4
(1 row)

There's still a problem with this implementation: the grammar
(copied from Postgres) accepts FILTER clauses on function calls that are
not aggregations. I need to figure out how to trap that - suggestions
welcomed!
Postgres does this:
test=# select abs(a) filter (where a>0) from t;
ERROR:  FILTER specified, but abs is not an aggregate function

test=# select i, rank() filter (where marker=true) over (order by i),
max(i) filter (where marker=true) over(order by i) from a;
ERROR:  FILTER is not implemented for non-aggregate window functions

Next I'll implement support for these clauses in window functions.