backupccl: properly propagate error when failing to commit job txn
This bug was introduced in 20.1. It means that any errors to commit the job
are not reported and instead an inscrutible error is reported.

```
 ERROR: cannot resume *backupccl.backupResumer job which is not committed
```

Fixes #54572.

Release note (bug fix): Fixed a bug which lead to inscrutible errors being
returned when creating a backup failed, for example, due to protected timestamp
limits.