workload: tpcc consistency check added flag as-of.
While running consistency checker on tpcc database and there is an
active workload tpcc workload running the consistency check fails
with retryable error like restart transaction:
TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError:.

To fix this adding a new flag `as-of` which allows to run consistency
check using `AS OF SYSTEM TIME`. This flag allows to pass value for
as of system time.

Epic: none

Release note: None