execerror: use errors package
We previously would unwrap a notVectorizedInternalError when first catching it,
which mean that we would lose that information and be unable to propagate its
underlying cause without annotating it if caught again (since we only check
for a *notVectorizedInternal wrapper). Instead, this patch changes the
CatchVectorizedRuntimeError function to leave the error object unwrapped when
doing its annotation. *notVectorizedInternalError is now enhanced so that it
can be sent over the wire unwrapped and propagated as many times as necessary
through CatchVectorizedRuntimeError without losing information.

Release note (bug fix): expected errors from the vectorized execution engine
are no longer mistakenly annotated as unexpected errors.